#!/bin/bash

module load openmpi
source activate cvxpy

TARGET=$(readlink -f "${1}")
OUTPUTDIR=$(readlink -f "${2}")
LABEL=$(basename "${SETUPFILE%.*}")
TIMESTAMP=$(date +"%y-%m-%d_%H-%M-%S")
TMPBASE="$TMP"

# echo "Running simulation with label ${LABEL}"
export CLUSTER_ID=$(date +"%y%m%d_%H%M%S")_${RANDOM}
TMPDIR="${TMPBASE}/${LABEL}_${CLUSTER_ID}"


echo "Changing into temporary directory ${TMPDIR}"
mkdir -pv "${TMPDIR}"
cd "${TMPDIR}"
cp -v "${TARGET}" .

echo "Launching cluster"
ipcontroller start --ip='*' --cluster-id="${CLUSTER_ID}" &
sleep 30
srun -n $SLURM_NTASKS ipengine start --cluster-id="${CLUSTER_ID}" &
sleep 30


echo "Launching job"
RUNFILE=$(basename "${TARGET}")
jupyter-nbconvert --to html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=600000 "${RUNFILE}"
echo "Done. Shutting done the server"
ipcontroller stop --cluster-id="${CLUSTER_ID}" &
sleep 10


echo "Copying files"
rm "$(basename ${TARGET})"
for f in *
do
    mv -v "${f}" "${OUTPUTDIR}/${f%.*}_${LABEL}_${TIMESTAMP}.${f##*.}"
done

echo "Cleaning up"
cd ..
rm -rv "${LABEL}_${CLUSTER_ID}"
